### ISSUE TITLE
Ruby gem: make Rababa useable from the CLI directly

### ISSUE THREAD

**Issue by ronaldtse** [interscript/rababa#24]
Ruby version needs to automatically download the necessary models and config.

The exe/rababa executable should be accessible.

Maybe this should be integrated into the Secryst framework?

**Comment by ronaldtse** [comment]
Need to add a CLI and a method to automatically download the latest trained models.

**Comment by ronaldtse** [comment]
@webdev778 is this done in #42 ?

**Comment by webdev778** [comment]
Done by this commit #bfa2a7dd69ba642060448706541ba3f8dbfccc1c
