### ISSUE TITLE
Auto-release rababa gem

### ISSUE THREAD

**Issue by ronaldtse** [interscript/rababa#27]
Use the secret `INTERSCRIPT_RUBYGEMS_API_KEY`.

**Comment by ronaldtse** [comment]
Copy release.yml from https://github.com/interscript/interscript/blob/master/.github/workflows/release.yml

**Comment by webdev778** [comment]
Done with this commit [538e11db](https://github.com/interscript/rababa/commit/538e11db77875cd15d52382d7c8195361c4b10d4)
