### ISSUE TITLE
Productionize ruby code for interscript https://github.com/interscript/rababa/tree/hebrew

### ISSUE THREAD

**Issue by gilgameshjw** [interscript/rababa#39]
@webdev778  @ronaldtse 
# Task on Hebrew branch
* Review and possibly improve the code and improve ruby style...
* Review and possibly the lib/Readme
* Create tests and gem
Current code can be used in rababa/lib using 

`ruby script.rb -m ../models-data/diacritization_model.onnx --t 'מה שלומך'`
`ruby script.rb -m ../models-data/diacritization_model.onnx --f '../python/data/test/test.txt'`

There is also a small sample data under rababa/example.

The hebrew diacritization model can be downloaded there https://github.com/secryst/rababa-models

**Comment by ronaldtse** [comment]
@webdev778 can you help refactor Rababa Ruby in order to incorporate this? Thanks.

**Comment by ronaldtse** [comment]
@webdev778 @gilgameshjw this task seems to be already completed in #42 , correct? If so please help close this. Thanks.

**Comment by webdev778** [comment]
yeah. already done
